apiVersion: v2
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/nodejs.png
name: reaction-admin
version: 0.1.0
appVersion: 0.1.0
