apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
 name: letsencrypt-prod
 namespace: cert-manager
spec:
 acme:
   email: <your-email>
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: cluster-issuer-account-key
   solvers:
   - http01:
       ingress:
         class: nginx

