fullnameOverride: "<deployment-name>"

hydra:
  config:
    serve:
      public:
        port: 4444
        cors:
          enabled: true
          allowed_origins:
            - https://<storefront-url>
            - https://<admin-url>
      admin:
        port: 4445
    secrets:
      system: <make-it-nice-and-long>
    dsn: <postgreSQL-connection-string>
    urls:
      self:
        issuer: https://<storefront-url>/auth
      login: https://<storefront-url>/idp/login
      consent: https://<storefront-url>/idp/consent
      logout: https://<storefront-url>/idp/logout
    oidc:
      subject_identifiers:
        enabled: true
        pairwise:
          salt: <add-a-good-salt>
  dangerousForceHttp: true // kubernetes internal communications is over http
  autoMigrate: true // seed the postgreSQL

service:
  public:
    port: 4444
  admin:
    port: 4445

ingress:
  public:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/proxy-body-size: 50mb
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: "<storefront-url>"
        paths: [ "/auth(/|$)(.*)" ]
    tls:
      - hosts:
          - "<storefront-url>"
        secretName: "<storefront-url-key>"
  admin:
    enabled: false
