{{- $fullName := include "reaction-admin.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $serviceHost := .Values.service.host -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-max-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-body-size: 50mb
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$2
  labels:
    app: {{ $fullName }}
  name: {{ $fullName }}-authentication
spec:
  rules:
    - host: {{ $serviceHost }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
            path: "/(authentication)(/|$)(.*)"
